# Generated by Django 6.0.1 on 2026-01-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='custom_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(choices=[('mbbs', 'MBBS'), ('md', 'MD'), ('ms', 'MS'), ('dip', 'Diploma'), ('phd', 'PhD'), ('other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('oncology', 'Oncology'), ('gastroenterology', 'Gastroenterology'), ('urology', 'Urology'), ('gynecology', 'Gynecology'), ('ophthalmology', 'Ophthalmology'), ('otolaryngology', 'Otolaryngology (ENT)'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('endocrinology', 'Endocrinology'), ('other', 'Other')], max_length=100),
        ),
    ]
